#!/usr/bin/env python3
import sys
from Lexer import lex 
 
def compile_file(input_file, output_file):
    with open(input_file, 'r') as file:
        code = file.read()

    tokens = lex (code)
    print(tokens)
    with open(output_file, 'w') as file:
        for token_type , token_value in tokens:
            file.write(f'{token_type}: {token_value}\n')

def main():
    # if len(sys.argv) != 3:
        # print("Usage: python compiler.py <input_file> <output_file>")
        # sys.exit(1)

    # input_file, output_file = sys.argv[1], sys.argv[2]
    # compile_file(input_file, output_file)
    data  = 'int	main	(	void)	{	return	0	;	}'
    data = lex(data)
    print(data)

if __name__ == "__main__":
    main()
